# Setup
title:        Castillo Lab of Humoral Immunology
tagline:      Welcome to the Castillo Lab at New Mexico State University
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author: Jorge C. Galarza Prieto
  name:       Jorge C. Galarza Prieto
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

# Others
markdown: kramdown
